---
title: Místnosti
views:
  - path: l
    icon: mdi:sofa
    badges:
      - type: entity
        entity: sensor.living_room_dining_light_controller_battery
      - type: entity
        entity: sensor.living_room_main_light_controller_battery
      - type: entity
        entity: sensor.living_room_shutter_controller_battery
      - type: entity
        entity: sensor.living_room_temperature_sensor_cf5ca3fe_power
      - type: entity
        entity: button.q8_max_full_cleaning
    cards:
      - type: entities
        entities:
          - entity: scene.watching_tv_night
          - entity: scene.all_lights_turned_off_except_hall
      - type: entities
        entities:
          - light.living_room_dining_light_big_light
          - light.living_room_dining_lights
          - light.living_room_dining_spotlight_center_light
          - light.living_room_dining_spotlight_left_light
          - light.living_room_dining_spotlight_right_light
          - light.living_room_kaja_light_level_light_color_on_off
          - light.living_room_stand_light_light
        title: Lights
      - type: entities
        entities:
          - entity: light.living_room_main_light
          - entity: light.living_room_main_light_outer_light
            name: Outer
          - entity: light.living_room_main_light_inner_light
            name: Inner
          - entity: switch.living_room_smart_socket_on_off
        title: Living room main light outer
        show_header_toggle: false
      - type: media-control
        entity: media_player.tv_samsung_q80_series_65
      - type: media-control
        entity: media_player.living_room_kodi
      - type: media-control
        entity: media_player.living_room_speaker
      - type: grid
        square: false
        columns: 1
        cards:
          - type: entities
            entities:
              - switch.living_room_soundbar_bass_boost
              - switch.living_room_soundbar_night_mode
              - switch.living_room_soundbar_voice_amplifier
          - type: media-control
            entity: media_player.living_room_soundbar
      - type: entities
        entities:
          - entity: sensor.living_room_dining_light_controller_battery
          - entity: sensor.living_room_kaja_light_controller_power
          - entity: sensor.living_room_shutter_controller_battery
          - entity: sensor.living_room_temperature_sensor_cf5ca3fe_power
      - type: entities
        entities:
          - sensor.living_room_temperature_sensor_cf5ca3fe_humidity
          - sensor.living_room_temperature_sensor_cf5ca3fe_temperature
      - type: entities
        entities:
          - entity: cover.living_room_shutters
          - entity: cover.obyvak_velke_stred
          - entity: cover.obyvak_velke_vlevo
          - entity: cover.obyvak_velke_vpravo
          - entity: cover.obyvak_vpravo
        title: Rolety obyvak
      - type: history-graph
        entities:
          - entity: sensor.living_room_temperature_sensor_cf5ca3fe_temperature
        hours_to_show: 48
        title: Living room temperature
        logarithmic_scale: false
      - type: grid
        square: false
        columns: 1
        cards:
          - type: entities
            entities:
              - vacuum.q8_max
              - button.q8_max_full_cleaning
              - select.q8_max_selected_map
              - sensor.q8_max_battery
              - binary_sensor.q8_max_charging
              - sensor.q8_max_last_clean_begin
              - sensor.q8_max_last_clean_end
          - type: picture
            image_entity: image.q8_max_map_0
  - icon: mdi:countertop
    badges:
      - type: entity
        entity: sensor.kitchen_light_remote_battery
    cards:
      - type: entities
        entities:
          - light.kitchen_counter_top_light
          - light.kitchen_light_light
        title: Lights
      - type: entities
        entities:
          - switch.pecici_trouba_power
          - switch.pecici_trouba_program_bottomheating
          - switch.pecici_trouba_program_frozenheatupspecial
          - switch.pecici_trouba_program_hotair
          - switch.pecici_trouba_program_hotairgrilling
          - switch.pecici_trouba_program_intensiveheat
          - switch.pecici_trouba_program_keepwarm
          - switch.pecici_trouba_program_pizzasetting
          - switch.pecici_trouba_program_preheating
          - switch.pecici_trouba_program_preheatovenware
          - switch.pecici_trouba_program_slowcook
          - switch.pecici_trouba_program_topbottomheating
          - switch.pecici_trouba_program_topbottomheatingeco
          - binary_sensor.pecici_trouba_door
          - sensor.pecici_trouba_duration
          - sensor.pecici_trouba_operation_state
          - sensor.pecici_trouba_program_progress
          - sensor.pecici_trouba_remaining_program_time
          - binary_sensor.pecici_trouba_remote_control
          - binary_sensor.pecici_trouba_remote_start
      - type: entities
        entities:
          - cover.kuchyne
  - icon: mdi:bed
    badges:
      - type: entity
        entity: sensor.bedroom_symfonisk_sound_remote_gen2_battery
      - type: entity
        entity: sensor.wardrobe_light_switch_battery
      - type: entity
        entity: sensor.bedroom_lamp_remote_power
    cards:
      - type: entities
        entities:
          - scene.bedroom_bright
          - scene.bedroom_dark
      - type: entities
        entities:
          - light.bedroom_bed_lamp_light
          - light.gledopto_gl_c_008p_light_2
          - light.wardrobe_light_light
        state_color: true
        show_header_toggle: true
        title: Lights
      - type: grid
        square: false
        columns: 1
        cards:
          - type: media-control
            entity: media_player.bedroom_speaker
          - type: entities
            entities:
              - number.bedroom_speaker_balance
              - number.bedroom_speaker_bass
              - switch.bedroom_speaker_crossfade
              - switch.bedroom_speaker_loudness
              - number.bedroom_speaker_treble
              - switch.sonos_alarm_1
              - switch.sonos_alarm_2
      - type: entities
        entities:
          - cover.loznice
          - cover.loznice_satna
  - icon: mdi:stairs
    badges:
      - type: entity
        entity: switch.eldes_alarm_pre_release
      - type: entity
        entity: person.petr_vavro
      - type: entity
        entity: person.hanka
      - type: entity
        entity: sensor.entry_hall_motion_sensoe_49a46e24_power
      - type: entity
        entity: sensor.entry_hall_switch_1_power
    cards:
      - type: entities
        entities:
          - entity: light.silicon_labs_ezsp_staircase_group_zha_group_0x0006
          - entity: light.staircase_light_level_light_color_on_off
          - entity: light.upstairs_light_light
          - entity: light.tasmota_toilet_light
          - entity: light.entry_hall_lights
          - entity: light.entry_hall_light_1_light
          - entity: light.entry_hall_light_2_light_3
          - entity: light.entry_hall_light_level_light_color_on_off
        title: Lights
      - type: entities
        entities:
          - switch.bathroom_hot_water_circulation_2
      - type: entities
        entities:
          - cover.schodiste
      - type: entities
        entities:
          - light.toilet_heater_switch_light
  - path: kids-room
    icon: mdi:teddy-bear
    cards:
      - type: entities
        entities:
          - light.kids_room_olivers_bed_light_light
          - light.kids_room_table_light_light
      - type: entities
        entities:
          - cover.detsky_pokoj
      - type: entities
        entities:
          - sensor.kids_room_temperature_humidity_sensor_humidity
          - sensor.kids_room_temperature_humidity_sensor_temperature
      - graph: line
        type: sensor
        entity: sensor.kids_room_temperature_humidity_sensor_temperature
        detail: 1
      - type: history-graph
        entities:
          - entity: sensor.kids_room_temperature_humidity_sensor_temperature
          - entity: sensor.kids_room_temperature_humidity_sensor_humidity
        logarithmic_scale: false
    badges:
      - type: entity
        entity: sensor.kids_room_olivers_bed_light_controller_battery
      - type: entity
        entity: sensor.kids_room_shutter_controller_battery
      - type: entity
        entity: sensor.kids_room_table_light_remote_battery
  - title: Kancelář
    path: kancelar
    icon: mdi:office-building
    visible:
      - user: 31d3f8d7f5c542d6aa3792fa2f63d91c
      - user: 77f52680eb7e41d49d220ba56320b239
    badges:
      - type: entity
        entity: sensor.ikea_of_sweden_remote_control_n2_d8c1e0fe_power
      - type: entity
        entity: sensor.office_shutter_controller_battery
    cards:
      - type: entities
        entities:
          - scene.office_video_konference_bright_sunlight
          - scene.office_work_hours
      - type: entities
        entities:
          - entity: light.office_lights
          - entity: light.signify_netherlands_b_v_lca001_huelight_2
          - entity: light.signify_netherlands_b_v_lca001_huelight
        title: Lights
      - type: grid
        square: false
        columns: 1
        cards:
          - type: entities
            entities:
              - entity: button.prusamini_cancel_job
              - entity: button.prusamini_pause_job
              - entity: button.prusamini_resume_job
              - entity: sensor.prusamini_filename
              - entity: sensor.prusamini_material
              - entity: sensor.prusamini_print_finish
              - entity: sensor.prusamini_print_speed
              - entity: sensor.prusamini_print_start
              - entity: sensor.prusamini_progress
              - entity: sensor.prusamini
            footer:
              type: buttons
              entities:
                - entity: scene.office_video_konference_bright_sunlight
                  show_icon: true
                  show_name: true
                - entity: scene.office_work_hours
                  show_icon: true
                  show_name: true
            title: Prusa mini
            show_header_toggle: false
            state_color: true
          - type: picture-entity
            entity: camera.prusamini_preview
      - type: entities
        entities:
          - entity: switch.office_printer_socket_switch
          - entity: device_tracker.samsung_c460_printer
          - entity: sensor.samsung_c460_series
      - type: entities
        entities:
          - cover.kancelar
  - path: garden
    badges: []
    cards:
      - type: entities
        entities:
          - switch.attic_switch
          - switch.garage_switch
      - type: entities
        entities:
          - switch.cerpadlo
          - switch.garden_lights
          - switch.not_connected_back_plugs
          - switch.pergola_plugs
          - sensor.zahrada_sonoff_4ch_pro_last_restart_time
          - sensor.zahrada_sonoff_4ch_pro_mqtt_connect_count
          - sensor.zahrada_sonoff_4ch_pro_restart_reason
          - sensor.zahrada_sonoff_4ch_pro_ssid
          - sensor.zahrada_sonoff_4ch_pro_wifi_connect_count
      - type: entities
        entities:
          - entity: binary_sensor.hunter_hc6_connectivity
          - entity: binary_sensor.kapka_vlevo_watering
          - entity: binary_sensor.kapka_vpravo_watering
          - entity: binary_sensor.zahrada_vpedu_watering
          - entity: binary_sensor.zahrada_vzadu_watering
          - entity: switch.kapka_vlevo_manual_watering
          - entity: switch.kapka_vpravo_manual_watering
          - entity: switch.zahrada_vpedu_manual_watering
          - entity: switch.zahrada_vzadu_manual_watering
          - entity: switch.kapka_vlevo_automatic_watering
          - entity: switch.kapka_vpravo_automatic_watering
          - entity: switch.zahrada_vpedu_automatic_watering
          - entity: switch.zahrada_vzadu_automatic_watering
          - entity: sensor.kapka_vlevo_watering_time
          - entity: sensor.kapka_vpravo_next_cycle
          - entity: sensor.kapka_vpravo_watering_time
          - entity: sensor.zahrada_vpedu_next_cycle
          - entity: sensor.zahrada_vpedu_watering_time
          - entity: sensor.zahrada_vzadu_next_cycle
          - entity: sensor.zahrada_vzadu_watering_time
    icon: mdi:tree
  - icon: mdi:car
    path: ""
    cards:
      - type: picture-entity
        entity: image.530d_xdrive_vehicle_image
        show_name: false
        show_state: false
      - type: entities
        title: Range & Mileage
        entities:
          - entity: sensor.530d_xdrive_vehicle_mileage
          - entity: sensor.530d_xdrive_range_tank_level
          - entity: sensor.530d_xdrive_range_tank_level_2
          - entity: sensor.530d_xdrive_range_total_range_last_sent
      - type: entities
        title: Doors & Openings
        entities:
          - entity: sensor.530d_xdrive_doors_overall_state
          - entity: binary_sensor.530d_xdrive_door_state_front_driver
          - entity: binary_sensor.530d_xdrive_door_state_front_passenger
          - entity: binary_sensor.530d_xdrive_door_state_rear_driver
          - entity: binary_sensor.530d_xdrive_door_state_rear_passenger
          - entity: binary_sensor.530d_xdrive_hood_state
          - entity: binary_sensor.530d_xdrive_tailgate_state
          - entity: binary_sensor.530d_xdrive_tailgate_door_state
      - type: entities
        title: Windows
        entities:
          - entity: sensor.530d_xdrive_window_state_front_driver
          - entity: sensor.530d_xdrive_window_state_front_passenger
          - entity: sensor.530d_xdrive_window_state_rear_driver
          - entity: sensor.530d_xdrive_window_state_rear_passenger
          - entity: sensor.530d_xdrive_sunroof_overall_state
          - entity: sensor.530d_xdrive_sunroof_state
      - type: entities
        title: Tyre Pressures
        entities:
          - entity: sensor.530d_xdrive_tire_pressure_front_left
          - entity: sensor.530d_xdrive_tire_pressure_front_right
          - entity: sensor.530d_xdrive_tire_pressure_rear_left
          - entity: sensor.530d_xdrive_tire_pressure_rear_right
      - type: map
        entities:
          - entity: device_tracker.530d_xdrive_location
        title: Location
  - path: default_view
    title: Home
    badges:
      - entity: sun.sun
    cards:
      - type: media-control
        entity: media_player.living_room_speaker
      - type: entities
        entities:
          - entity: switch.garden_lights
          - entity: switch.pergola_plugs
          - entity: switch.cerpadlo
          - entity: switch.not_connected_back_plugs
          - entity: switch.attic_switch
          - entity: switch.garage_switch
        title: Zahrada
      - type: weather-forecast
        entity: weather.domov
        show_forecast: false
      - type: entities
        entities:
          - cover.detsky_pokoj
          - cover.kancelar
          - cover.kuchyne
          - cover.loznice
          - cover.loznice_satna
          - cover.obyvak_velke_stred
          - cover.obyvak_velke_vlevo
          - cover.obyvak_velke_vpravo
          - cover.obyvak_vpravo
          - cover.schodiste
        title: cover
      - type: entities
        entities:
          - entity: scene.office_video_konference_bright_sunlight
          - entity: scene.office_work_hours
          - entity: light.entry_hall_lights
          - entity: light.signify_netherlands_b_v_lca001_huelight
          - entity: cover.kancelar
          - entity: switch.living_room_smart_socket_on_off
      - type: entities
        entities:
          - entity: light.living_room_dining_light_big_light
          - entity: light.living_room_dining_spotlight_center_light
          - entity: light.living_room_dining_spotlight_left_light
          - entity: light.living_room_dining_spotlight_right_light
          - entity: light.kitchen_light_light
          - entity: light.kitchen_counter_top_light
          - entity: light.living_room_stand_light_light
        title: Světlo
      - type: entities
        entities:
          - switch.bathroom_hot_water_circulation_2
          - light.tasmota_toilet_light
        title: Vypínač
      - type: picture-elements
        elements:
          - type: state-badge
            entity: binary_sensor.clt_l29_is_charging
            style:
              top: 32%
              left: 40%
        image: /local/images/Ground-Floorplan.png
      - type: entities
        entities:
          - entity: sensor.prusamini
          - entity: sensor.prusamini_filename
          - entity: camera.prusamini_preview
          - entity: sensor.prusamini_print_finish
          - entity: sensor.prusamini_print_start
          - entity: sensor.prusamini_progress
          - entity: button.prusamini_resume_job
          - entity: button.prusamini_pause_job
          - entity: button.prusamini_cancel_job
        title: Prusa Mini
