---
name: Home Assistant CI

# yamllint disable-line rule:truthy
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["**"]
  schedule:
    - cron: "0 6 * * *"

jobs:
  home-assistant:
    name: "Home Assistant ${{ matrix.version }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["stable", "beta"]
    steps:
      - name: Check out configuration from GitHub
        uses: actions/checkout@v4

      - name: Run Home Assistant Configuration Check
        uses: frenck/action-home-assistant@v1.4
        with:
          path: "."
          secrets: ./secrets.fake.yaml
          version: "${{ matrix.version }}"
